// src/components/pages/ServiceVsGroups/ServiceRegionAvailabilityModal.vue
<template>
  <b-modal
    id="service-region-availability-modal"
    :title="service ? `'${service.name}' is available at:` : ''"
    :no-fade="true"
    :hide-footer="true"
    scrollable
    :body-class="'p-none'"
  >
    <table class="table" v-if="service">
      <tr v-for="(idx,key) in serviceAvailability">
        <th>
          {{regionTitle(key)}}
          <span class="text-black-50">
            ({{key}})
          </span>
        </th>
        <td>
          <span class="region-availability"
                :class="computeAvailabilityClass(service.availability[key])"
          >&nbsp;</span>
          {{service.availability[key].inGA ? 'GA' : ''}}
          {{service.availability[key].inPreview ? 'Preview' : ''}}
          {{service.availability[key].expectation ? service.availability[key].expectation : ''}}
        </td>
      </tr>
    </table>
  </b-modal>
</template>

<script>
export default {
  name: 'ServiceRegionAvailabilityModal',
  data: function () {
    return {
      service: null
    }
  },
  mounted: function () {
    this.$root.$on('app::services::region-availability-modal::show', this.showModal)
  },
  computed: {
    serviceAvailability: function () {
      return SL.filterServiceAvailabilityByRegionFilter(this.service.availability)
    }
  },
  methods: {
    regionTitle: function(key) {
      return SL.regionsDic[key]
    },
    computeAvailabilityClass: function(av) {
      if (av.inGA) {
        return 'region-availability-ga'
      } else if (av.inPreview) {
        return 'region-availability-preview'
      } else if (av.expectation) {
        return 'region-availability-expected'
      }
      return ''
    },
    showModal: function (event, serviceId) {
      let that = this
      this.service = null

      this.$nextTick( function(){
        that.service = SL.services[serviceId] || null
        if (!this.service) {
          //console.warn('Service is NULL, skip init modal')
          return
        }
        that.$root.$emit('bv::show::modal', 'service-region-availability-modal', event)
      })
    }
  }
}
</script>

// src/scenes/LandingScene/components/ServiceRegionAvailabilityModal.jsx
import React, {useState, useEffect} from 'react'
import PropTypes from 'prop-types'
import Modal from 'react-bootstrap/Modal'
import ServiceLinking from 'src/services/ServiceLinking';

const ServiceRegionAvailabilityModal = props => {

  let [service, setService] = useState(null)

  useEffect( () => {
    onSelectService(props.serviceId)
  }, [props.serviceId])

  const onSelectService = serviceId => {
    let exist = ServiceLinking.findServiceById(serviceId)
    if (exist) {
      setService(exist)
    } else {
      console.error(`The service was not found`)
    }
  }

  if (null === service) {
    return ''
  }

  const {serviceId, ...rest} = props

  const computeAvailabilityClass = av => {
    if (av.inGA) {
      return 'region-availability-ga'
    } else if (av.inPreview) {
      return 'region-availability-preview'
    } else if (av.expectation) {
      return 'region-availability-expected'
    }
    return ''
  }

  const filteredServiceAvailability = ServiceLinking.filterServiceAvailabilityByRegionFilter(service.availability)

  return (
    <Modal {...rest} scrollable>
      <Modal.Header closeButton>
        <Modal.Title >
          {service ? `${service.name} available at:` : ''}
        </Modal.Title>
      </Modal.Header>
      <Modal.Body className="show-scroll-always">
        <table className="table table-hover">
          <thead></thead>
          <tbody>
            {
              Object.keys(filteredServiceAvailability).map( (key, idx) => {
                return (
                  <tr key={idx} className="table">
                    <th>
                      {ServiceLinking.regionsDic[key]}
                      <br/>
                      <span className="text-muted">
                        {key}
                      </span>
                    </th>
                    <td>
                      <span className={`region-availability ${computeAvailabilityClass(service.availability[key])}`}>
                      
                      </span>
                      <span className="ml-2">
                        {service.availability[key].inGA ? 'GA' : ''}
                        {service.availability[key].inPreview ? 'Preview' : ''}
                        {service.availability[key].expectation ? service.availability[key].expectation : ''}
                      </span>
                    </td>
                  </tr>
                )
              })
            }
          </tbody>
          <tfoot></tfoot>
        </table>
      </Modal.Body>
      
    </Modal>
  );
}

ServiceRegionAvailabilityModal.propTypes = {
  serviceId: PropTypes.string.isRequired
}

export default ServiceRegionAvailabilityModal
